name: Nicole Franco
favicon: null
layout_spectrum: 0.47702581039629877
typography_spectrum: 0.8545988544356078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.27607570798136294
  lightness: 0.6331919718068093
  saturation: 0.28811562480404973
  rhythmicContrast: 0.6387771894223988
purpose: []
